# Generated by Django 6.0.6 on 2026-06-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('PREPAID', 'PREPAID'), ('CASH_ON_PICKUP', 'CASH_ON_PICKUP'), ('UPI_ON_PICKUP', 'UPI_ON_PICKUP'), ('CARD_ON_PICKUP', 'CARD_ON_PICKUP')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED'), ('PARTIALLY_REFUNDED', 'PARTIALLY_REFUNDED')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_HANDOVER', 'PENDING_HANDOVER'), ('HANDED_OVER', 'HANDED_OVER')], default='PENDING_HANDOVER', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to=settings.AUTH_USER_MODEL)),
                ('handed_over_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_handovers_received', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_ledgers', to='stores.store')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_ledger', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('NOT_REQUIRED', 'NOT_REQUIRED'), ('REFUND_IN_PROGRESS', 'REFUND_IN_PROGRESS'), ('REFUND_COMPLETED', 'REFUND_COMPLETED'), ('REFUND_FAILED', 'REFUND_FAILED')], default='NOT_REQUIRED', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.orderitem')),
            ],
        ),
    ]
