# Generated by Django 6.0.6 on 2026-07-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashledger',
            name='supervisor_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
