# Generated by Django 6.0.6 on 2026-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cashledger_supervisor_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('PREPAID', 'PREPAID'), ('CASH_ON_PICKUP', 'CASH_ON_PICKUP'), ('UPI_ON_PICKUP', 'UPI_ON_PICKUP'), ('CARD_ON_PICKUP', 'CARD_ON_PICKUP')], max_length=20, null=True),
        ),
    ]
