# Generated by Django 6.0.6 on 2026-08-20 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_store'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('password_hash', models.CharField(max_length=150, unique=True)),
                ('requested_role', models.CharField(choices=[('PACKER', 'PACKER'), ('TAKEAWAY_STAFF', 'TAKEAWAY_STAFF'), ('SUPERVISOR', 'SUPERVISOR')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_registration_requests', to='stores.store')),
            ],
        ),
    ]
