# Generated by Django 6.0.6 on 2026-08-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffregistrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistrationrequest',
            name='password_hash',
        ),
    ]
