# Generated by Django 6.0.6 on 2026-08-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_staffregistrationrequest_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistrationrequest',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
