# Generated by Django 6.0.6 on 2026-06-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('order_status', models.CharField(choices=[('ORDER_PLACED', 'ORDER_PLACED'), ('PACKING_IN_PROGRESS', 'PACKING_IN_PROGRESS'), ('PACKING_DONE', 'PACKING_DONE'), ('BOX_ASSIGNED', 'BOX_ASSIGNED'), ('OUT_FOR_PICKUP', 'OUT_FOR_PICKUP'), ('VERIFICATION_IN_PROGRESS', 'VERIFICATION_IN_PROGRESS'), ('REPLACEMENT_PENDING_APPROVAL', 'REPLACEMENT_PENDING_APPROVAL'), ('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('READY_FOR_FINAL_HANDOVER', 'READY_FOR_FINAL_HANDOVER'), ('PICKED_UP', 'PICKED_UP'), ('ORDER_CANCELLED', 'ORDER_CANCELLED')], default='ORDER_PLACED', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED'), ('PARTIALLY_REFUNDED', 'PARTIALLY_REFUNDED')], default='PENDING', max_length=20)),
                ('refund_status', models.CharField(choices=[('NOT_REQUIRED', 'NOT_REQUIRED'), ('REFUND_IN_PROGRESS', 'REFUND_IN_PROGRESS'), ('REFUND_COMPLETED', 'REFUND_COMPLETED'), ('REFUND_FAILED', 'REFUND_FAILED')], default='NOT_APPLICABLE', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('out_for_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELLED', 'CANCELLED'), ('REPLACED', 'REPLACED')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
        ),
    ]
