# Generated by Django 6.0.6 on 2026-06-25 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_from_store_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_mode',
            field=models.CharField(choices=[('DELIVERY', 'DELIVERY'), ('TAKEAWAY', 'TAKEAWAY')], default='DELIVERY', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='replacement_resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PickupCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_completion_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('box_id', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_scan_status', models.BooleanField(default=False)),
                ('qr_scan_time', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_status', models.BooleanField(default=False)),
                ('otp_verification_time', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(blank=True, max_length=30, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_items', models.JSONField(blank=True, default=list)),
                ('replaced_items', models.JSONField(blank=True, default=list)),
                ('replacement_reasons', models.JSONField(blank=True, default=list)),
                ('supervisor_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('picked_up_at', models.DateTimeField()),
                ('final_order_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_completions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_completion', to='orders.order')),
                ('packer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_pickup_completions', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_pickups', to=settings.AUTH_USER_MODEL)),
                ('takeaway_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_pickups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('replacement_quantity', models.PositiveIntegerField(default=1)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.orderitem')),
                ('replacement_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests', to='products.product')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeoutCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('reason', models.CharField(default='pickup timeout > 30 min', max_length=100)),
                ('out_for_pickup_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField()),
                ('item_wise_stock_restored_details', models.JSONField(blank=True, default=list)),
                ('refund_initiated', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('box_released', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeout_cancellation', to='orders.order')),
            ],
        ),
    ]
