# Generated by Django 6.0.6 on 2026-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer_latitude_order_customer_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'NOT_REQUIRED'), ('REFUND_IN_PROGRESS', 'REFUND_IN_PROGRESS'), ('REFUND_COMPLETED', 'REFUND_COMPLETED'), ('REFUND_FAILED', 'REFUND_FAILED')], default='NOT_REQUIRED', max_length=20),
        ),
    ]
