# Generated by Django 6.0.6 on 2026-07-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_id_alter_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER_PLACED', 'ORDER_PLACED'), ('PACKING_IN_PROGRESS', 'PACKING_IN_PROGRESS'), ('PACKING_DONE', 'PACKING_DONE'), ('BOX_ASSIGNED', 'BOX_ASSIGNED'), ('MARK_OUT_FOR_DELIVERY', 'MARK_OUT_FOR_DELIVERY'), ('OUT_FOR_PICKUP', 'OUT_FOR_PICKUP'), ('VERIFICATION_IN_PROGRESS', 'VERIFICATION_IN_PROGRESS'), ('REPLACEMENT_PENDING_APPROVAL', 'REPLACEMENT_PENDING_APPROVAL'), ('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('READY_FOR_FINAL_HANDOVER', 'READY_FOR_FINAL_HANDOVER'), ('PICKED_UP', 'PICKED_UP'), ('ORDER_CANCELLED', 'ORDER_CANCELLED')], default='ORDER_PLACED', max_length=50),
        ),
    ]
