# Generated by Django 6.0.6 on 2026-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_is_verified_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
