# Generated by Django 6.0.6 on 2026-07-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('WRONG_ITEM', 'Wrong Item Packed'), ('DAMAGED_ITEM', 'Damaged Item'), ('ITEM_MISSING', 'Item Missing'), ('CUSTOMER_DECLINED', 'Customer Declined Item'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
