# Generated by Django 6.0.6 on 2026-07-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_cancellation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementrequest',
            name='decision_note',
        ),
        migrations.RemoveField(
            model_name='replacementrequest',
            name='replacement_product',
        ),
        migrations.RemoveField(
            model_name='replacementrequest',
            name='replacement_quantity',
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='supervisor_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
    ]
