# Generated by Django 6.0.6 on 2026-07-10 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_replacementrequest_decision_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.orderitem'),
        ),
    ]
