# Generated by Django 6.0.6 on 2026-07-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_replacementrequest_order_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='replacement_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests', to='products.product'),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='reason',
            field=models.CharField(choices=[('DAMAGED_ITEM', 'Damaged Item'), ('WRONG_ITEM', 'Wrong Item Packed'), ('QUALITY_ISSUE', 'Quality Issue'), ('PACKAGING_DAMAGE', 'Packaging Damage'), ('ITEM_MISSING', 'Item Missing'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
