# Generated by Django 6.0.6 on 2026-07-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_replacementrequest_replacement_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replacementrequest',
            old_name='approved_by',
            new_name='decided_by',
        ),
    ]
