# Generated by Django 6.0.6 on 2026-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_otp_attempts_order_otp_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_verified',
            field=models.BooleanField(default=False),
        ),
    ]
