# Generated by Django 6.0.6 on 2026-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_pickup_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_verified_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
