# Generated by Django 6.0.6 on 2026-08-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_cancellation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
    ]
