# Generated by Django 6.0.6 on 2026-08-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('PAY_AT_TAKEAWAY', 'Pay at Takeaway')], default='PREPAID', max_length=20),
        ),
    ]
