# Generated by Django 6.0.6 on 2026-07-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0014_pickuphistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PICKUP_READY', 'Pickup Ready'), ('ORDER_CANCELLED', 'Order Cancelled'), ('REPLACEMENT_APPROVED', 'Replacement Approved'), ('REPLACEMENT_REJECTED', 'Replacement Rejected'), ('PAYMENT_RECEIVED', 'Payment Received'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed'), ('PICKUP_COMPLETED', 'Pickup Completed')], default='PICKUP_READY', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
