# Generated by Django 6.0.6 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PICKUP_READY', 'Pickup Ready'), ('ORDER_CANCELLED', 'Order Cancelled'), ('REPLACEMENT_APPROVED', 'Replacement Approved'), ('REPLACEMENT_REJECTED', 'Replacement Rejected'), ('PAYMENT_RECEIVED', 'Payment Received'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed'), ('PICKUP_COMPLETED', 'Pickup Completed')], max_length=40),
        ),
    ]
